/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_heaven7_android_FreetypeTests */

#ifndef _Included_com_heaven7_android_FreetypeTests
#define _Included_com_heaven7_android_FreetypeTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_heaven7_android_FreetypeTests
 * Method:    writeTga
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_heaven7_android_FreetypeTests_writeTga
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
